import './globals.css';
import { Roboto_Condensed } from 'next/font/google';
import { Toaster } from 'react-hot-toast'; // ✅ Import toast provider

const inter = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster position="bottom-center" /> {/* ✅ Toast notification container */}
      </body>
    </html>
  );
}
